remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: NetAcquire Learning Materials
description: Materials to teach the ins and outs of use and development on NetAcquire servers

show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]